# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtlantaTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_text', models.CharField(blank=True, max_length=160)),
                ('medium_text', models.CharField(blank=True, max_length=96)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
