# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_dataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtlantaTree',
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_name',
            field=models.CharField(default='dummy', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='format',
            field=models.CharField(default='dummy', max_length=16),
            preserve_default=False,
        ),
    ]
