# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_dataset_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('format', models.CharField(choices=[('csv', 'csv'), ('excel', 'excel'), ('shapefile', 'shapefile')], max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='datafile',
            name='dataset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Dataset'),
        ),
        migrations.AlterUniqueTogether(
            name='datafile',
            unique_together=set([('dataset_id', 'name')]),
        ),
    ]
