# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20170622_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='num_records',
            field=models.IntegerField(null=True),
        ),
    ]
