# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_metadata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=set([('dataset_id', 'feature')]),
        ),
    ]
