# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20170623_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metadata',
            new_name='MetaInfo',
        ),
    ]
