"use strict";

const ActionTypes = {
    INITIALIZE_STATE: 'INITIALIZE_STATE',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',

    // REQUEST_RECORDS: 'REQUEST_RECORDS',
    // RECEIVE_RECORDS: 'RECEIVE_RECORDS',
};

export default ActionTypes;