'use strict'

const ActionTypes = {
    INITIALIZE_STATE: 'INITIALIZE_STATE',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
    FETCH_RECORDS: 'FETCH_RECORDS',
    RECEIVE_RECORDS: 'RECEIVE_RECORDS',
    CANCEL_FETCHING: 'CANCEL_FETCHING',
    SELECT_TAB: 'SELECT_TAB',
}

export default ActionTypes