'use strict'

const ActionTypes = {
    INITIALIZE_STATE: 'INITIALIZE_STATE',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
    SELECT_TAB: 'SELECT_TAB',
    TOGGLE_IMAGE: 'TOGGLE_IMAGE',
    FETCH_RECORDS: 'FETCH_RECORDS',
    RECEIVE_RECORDS: 'RECEIVE_RECORDS',
    CANCEL_FETCHING: 'CANCEL_FETCHING',
    FETCH_META: 'FETCH_META',
    RECEIVE_META: 'RECEIVE_META',
    CANCEL_FETCHING_META: 'CANCEL_FETCHING_META',
}

export default ActionTypes