# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96)),
                ('collector', models.CharField(max_length=64)),
                ('date_from', models.CharField(max_length=16)),
                ('date_to', models.CharField(max_length=16, null=True)),
                ('file_name', models.CharField(max_length=64)),
            ],
        ),
    ]
