# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='email',
            field=models.EmailField(default='tonnpa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='nickname',
            field=models.CharField(default='tonnpa', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='submission_date',
            field=models.DateField(default=datetime.date(2017, 11, 12)),
        ),
        migrations.AddField(
            model_name='contribution',
            name='username',
            field=models.CharField(default='Tom Nguyen', max_length=64),
            preserve_default=False,
        ),
    ]
